### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Raganius** [iotaledger/iri-snapcraft#1]
Following the install instructions, after I clone the project in a local directory and run "snapcraft", it starts building, but I get the following error in the end:
`Checking connectivity... done.
Preparing to pull exec
Pulling exec
Preparing to build iri
/home/abulafia/iota/IRIsnapcraft/iri-snapcraft/parts/iri/install/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts will be a dangling symlink
Building iri
mvn package
[INFO] Scanning for projects...
[INFO]                                                                        
[INFO] ------------------------------------------------------------------------
[INFO] Building IRI 1.1.0
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.664 s
[INFO] Finished at: 2016-11-14T11:46:24-05:00
[INFO] Final Memory: 9M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Command '['/bin/sh', '/tmp/tmpjf10isvh', 'mvn', 'package']' returned non-zero exit status 1`

Here are the contents left inside the "iri-snapcraft" directory:
`parts
prime
README.md
snapcraft.yaml
stage
wrapper.sh`

**Comment by davassi** [comment]
investigating...

**Comment by davassi** [comment]
This issue can be solved by executing:

$ sudo apt-get install --reinstall ca-certificates-java
